{% set name = "cppbktree" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cppbktree-{{ version }}.tar.gz
  sha256: e88addff2fe44e3194e2408e6beb008598a762d996de3b3e353d624ab0792c0c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - pip
    - python
  run:
    - python

test:
  imports:
    - cppbktree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mxmlnkn/cppbktree
  summary: C++ Implementation of a Burkhard-Keller Tree (BK-Tree)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
